version: '3.4'

services:
  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/AuthenticationAPI/Dockerfile
    ports:
        - "5020:443"
        - "5050:80"

  messageapi:
    image: ${DOCKER_REGISTRY-}messageapi
    build:
      context: .
      dockerfile: MessageAPI/MessageAPI/Dockerfile
    ports:
        - "5021:443"
        - "5051:80"
    depends_on: 
      - db

  timelineapi:
    image: ${DOCKER_REGISTRY-}timelineapi
    build:
      context: .
      dockerfile: TimelineAPI/TimelineAPI/Dockerfile
    ports:
        - "5022:443"
        - "5052:80"
    depends_on: 
      - db

  tweetapi:
    image: ${DOCKER_REGISTRY-}tweetapi
    build:
      context: .
      dockerfile: TweetAPI/TweetAPI/Dockerfile
    ports:
        - "5023:443"
        - "5053:80"
    depends_on: 
      - db

  userprofileapi:
    image: ${DOCKER_REGISTRY-}userprofileapi
    build:
      context: .
      dockerfile: UserProfileAPI/UserProfileAPI/Dockerfile
    ports:
        - "5024:443"
        - "5054:80"
    depends_on: 
      - db

  db:
    image: mariadb
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - dbdata:/var/lib/mysql

  pma:
    depends_on: 
     - db
    image: phpmyadmin/phpmyadmin  
    container_name: pma
    restart: always
    ports:
     - '80:80'
    environment: 
     PMA_HOST: db
  
volumes:
 dbdata: