version: '3.4'

services:
  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/AuthenticationAPI/Dockerfile
    ports:
        - "5050:80"

  messageapi:
    image: ${DOCKER_REGISTRY-}messageapi
    build:
      context: .
      dockerfile: MessageAPI/MessageAPI/Dockerfile
    ports:
        - "5051:80"

  timelineapi:
    image: ${DOCKER_REGISTRY-}timelineapi
    build:
      context: .
      dockerfile: TimelineAPI/TimelineAPI/Dockerfile
    ports:
        - "5052:80"

  tweetapi:
    image: ${DOCKER_REGISTRY-}tweetapi
    build:
      context: .
      dockerfile: TweetAPI/TweetAPI/Dockerfile
    ports:
        - "5053:80"

  userprofileapi:
    image: ${DOCKER_REGISTRY-}userprofileapi
    build:
      context: .
      dockerfile: UserProfileAPI/UserProfileAPI/Dockerfile
    ports:
        - "5054:80"

  tweetdb:
    image: mariadb
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - tweetdata:/var/lib/mysql

  messagingdb:
    image: mariadb
    ports:
        - "3308:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - messagingdata:/var/lib/mysql

  usersdb:
    image: mariadb
    ports:
        - "3309:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - usersdata:/var/lib/mysql

  userpma:
    depends_on: 
     - usersdb
    image: phpmyadmin/phpmyadmin  
    container_name: userpma
    restart: always
    ports:
     - '80:80'
    environment: 
     PMA_HOST: usersdb
   
  messagingpma:
    depends_on: 
     - messagingdb
    image: phpmyadmin/phpmyadmin  
    container_name: messagingpma
    restart: always
    ports:
     - '81:80'
    environment: 
     PMA_HOST: messagingdb

  tweetpma:
    depends_on: 
     - tweetdb
    image: phpmyadmin/phpmyadmin  
    container_name: tweetpma
    restart: always
    ports:
     - '82:80'
    environment: 
     PMA_HOST: tweetdb

volumes:
 usersdata:
 tweetdata:
 messagingdata:
