on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout source code
       uses: actions/checkout@v3

     - uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

     - run: |
         az account show